---
- hosts: repohost1

  vars:
    repoid: epel
    repodir: /var/www/html
    logdir: /var/log/repo
    logdate: "{{ lookup('pipe','date +%d%m%Y_%H%M%S') }}"

  tasks:
  - name: Repo logs directory
    file: "{{ logdir }}"
    state: directory
  - name: Repo data directory
    file:
      path: "{{ repodir }}/{{ repoid }}"
      state: directory
      owner: apache
      group: wheel
      mode: 0755

  - name: Log repo state before the sync
    shell: "ls -ltr {{ repodir }}/{{ repoid }}/Packages > {{ logdir }}/{{ repoid }}.{{ logdate }}.pre_sync.log 2>&1"

  - name: Sync yum repos to a local directory
    shell: reposync -r {{ repoid }} -p {{ repodir }}
  - name: Create the rpm metadata
    shell: createrepo {{ repodir }}/{{ repoid }}

  - name: List of new packages downloaded
    shell: "cat {{ logdir }}/{{ repoid }}.{{ logdate }}.sync.log | grep Downloading | /bin/awk -F'/' '{print $2}' > {{ logdir }}/{{ repoid }}.{{ logdate }}.diff.log 2>&1"
  - name: Log repo state after the sync
    shell: "ls -ltr {{ repodir }}/{{ repoid }}/Packages > {{ logdir }}/{{ repoid }}.{{ logdate }}.post_sync.log 2>&1"


