---
- hosts: repohost1

  vars:
    repoid: ['epel', 'rhel-6-server-rpms', 'rhel-6-server-optional-rpms', 'rhel-6-sever-extras-rpms']
    repodir: /var/www/html
    logdir: /var/log/repo
    logdate: "{{ lookup('pipe','date +%d%m%Y_%H%M%S') }}"

  tasks:
  - name: Repo logs directory
    file:
      path: "{{ logdir }}"
      state: directory
  - name: Repo data directory
    file:
      path: "{{ repodir }}/{{ item }}"
      state: directory
      owner: apache
      group: wheel
      mode: 0755
    with_items:
      - "{{ repoid }}"

  - name: Log repo state before the sync
    shell: "ls -ltr {{ repodir }}/{{ item }}/Packages > {{ logdir }}/{{ item }}.{{ logdate }}.pre_sync.log 2>&1"
    with_items:
      - "{{ repoid }}"

  - name: Sync yum repos to a local directory
    shell: reposync -r {{ item }} -p {{ repodir }} >> {{ logdir }}/{{ item }}.{{ logdate }}.sync.log 2>&1"
    with_items:
      - "{{ repoid }}
  - name: Create the rpm metadata
    shell: createrepo {{ repodir }}/{{ item }}
    with_items:
      - "{{ repoid }}

  - name: List of new packages downloaded
    shell: "cat {{ logdir }}/{{ item }}.{{ logdate }}.sync.log | grep Downloading | /bin/awk -F'/' '{print $2}' > {{ logdir }}/{{ item }}.{{ logdate }}.diff.log 2>&1"
    with_items:
      - "{{ repoid }}"
  - name: Log repo state after the sync
    shell: "ls -ltr {{ repodir }}/{{ item }}/Packages > {{ logdir }}/{{ item }}.{{ logdate }}.post_sync.log 2>&1"
    with_items:
      - "{{ repoid }}"


